### PR TITLE
Fixes the release for BYOND 511

### PR DESCRIPTION
**Pull request by ZeWaka**
There was an incorrect var lookup in the process scheduler that apparently worked without incident for at least a year somehow???

See lines 136 and 221.

:imcoder: 

Edit: There were further things pushed to my branch. You'll want to use those as well.

### CODE REVIEW

**Comment by volundr-** [comment]
This repository has chosen to disable pull requests.

**Comment by volundr-** [comment]
This repository has chosen to disable pull requests.

**Comment by Iamgoofball** [comment]
Haine, there's a toggle in the repo settings to disable that bot

**Comment by EclectusInfectus** [comment]
I manually committed the file in https://github.com/goonstation/goonstation-2016/commit/4dee7848081fa1d5c629051bc687eeefe7d3822c because I couldn't figure out how exactly to turn off volundr, or as somepotato told me to say "I did the thing"

**Pull request closed without merging**
