### PR TITLE
Adds Comic Sans and Wingdings as a font.

### PR DESCRIPTION
**Pull request by Iamgoofball**
dreamseeker_2016-03-02_17-45-33
dreamseeker_2016-03-02_17-49-38
dreamseeker_2016-03-02_17-44-43

first PR to goonstation

### CODE REVIEW

**Comment by Boxe** [comment]
and there he is

**Comment by ZeWaka** [comment]
:+1:

**Comment by ghost** [comment]
Goonstation will never be the same

It will be just better

**Comment by DrCelt** [comment]
I figured it out.
The reason why goofcode is shite
It's because he was all this time trying to copy goon. He did a poor job of it honestly though, his code is better.

**Comment by AliiTea** [comment]
This is great

**Comment by volundr-** [comment]
See [Readme](https://github.com/goonstation/goonstation-2016/blob/master/README.md), thanks!

**Pull request closed without merging**
